### PR TITLE
Update node sass to 2.0.1

### PR DESCRIPTION
**Pull request by deepflame**
needed to update node sass to 2.0.1 to make it compile on Node 0.12 .

### CODE REVIEW

**Comment by deepflame** [comment]
Hmm, weird. I get the following error now:

```
16:47:46 ember.1 | `libsass` bindings not found. Try reinstalling `node-sass`?
16:47:46 ember.1 | Error: `libsass` bindings not found. Try reinstalling `node-sass`?
16:47:46 ember.1 |     at getBinding (/Users/aboehrnsen/Developer/frontrunnerio/clients/node/APP/northapp-staging/frontend/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:22:11)
16:47:46 ember.1 |     at Object.<anonymous> (/Users/aboehrnsen/Developer/frontrunnerio/clients/node/APP/northapp-staging/frontend/node_modules/broccoli-sass/node_modules/node-sass/lib/index.js:188:23)
16:47:46 ember.1 |     at Module._compile (module.js:460:26)
16:47:46 ember.1 |     at Object.Module._extensions..js (module.js:478:10)
16:47:46 ember.1 |     at Module.load (module.js:355:32)
16:47:46 ember.1 |     at Function.Module._load (module.js:310:12)
16:47:46 ember.1 |     at Module.require (module.js:365:17)
16:47:46 ember.1 |     at require (module.js:384:17)
16:47:46 ember.1 |     at Object.<anonymous> (/Users/aboehrnsen/Developer/frontrunnerio/clients/node/APP/northapp-staging/frontend/node_modules/broccoli-sass/index.js:5:12)
16:47:46 ember.1 |     at Module._compile (module.js:460:26)
```

Also reinstalling does not help.

Please use this with care. It needs more testing.

**Comment by mordack** [comment]
I'm actually getting something different when I run ```ember server``` with a local checkout of your branch:

```
undefined is not a function
TypeError: undefined is not a function
    at /Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/index.js:50:10
    at $$$internal$$initializePromise (/Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/node_modules/rsvp/dist/rsvp.js:538:9)
    at new $$rsvp$promise$$Promise (/Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/node_modules/rsvp/dist/rsvp.js:851:9)
    at SassCompiler.updateCache (/Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/index.js:34:10)
    at /Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/node_modules/broccoli-caching-writer/index.js:92:34
    at $$$internal$$tryCatch (/Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/node_modules/rsvp/dist/rsvp.js:490:16)
    at $$$internal$$invokeCallback (/Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/node_modules/rsvp/dist/rsvp.js:502:17)
    at $$$internal$$publish (/Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/node_modules/rsvp/dist/rsvp.js:473:11)
    at $$rsvp$asap$$flush (/Users/ewout/Workspace/_Code/JavaScript/nginx-status/node_modules/broccoli-sass/node_modules/rsvp/dist/rsvp.js:1581:9)
    at process._tickCallback (node.js:355:11)
```

Which is exactly the same as I got when I did some fiddling around this afternoon.

It seems that ```sass.renderFile``` has been removed from node-sass and replaced with ```sass.render```, which calls the exported C++ ```renderFile``` binding if the passed in options argument has a falsy ```data``` property [here](https://github.com/sass/node-sass/blob/master/lib/index.js#L220). Looking at the C++ code it seems that nothing was changed under the hood.
After changing [this](https://github.com/joliss/broccoli-sass/blob/master/index.js#L50) line from ```sass.renderFile``` to ```sass.render``` and running ```ember server```, the exception was gone, but no css file was written to the ```outFile``` path and I got a 404 in the browser.

I went looking for issues/pull requests in the node-sass repository and came across an issue which I can't seem to find any more, which mentioned something that ```sass.render``` always returns the compiled output in the success callback as the first argument. When logging the success callback's result arg, this is what I got:

```
{ css: '.container {\n  margin-top: 50px; }\n\n',
  map: '{}',
  stats:
   { entry: '/Users/ewout/Workspace/_Code/JavaScript/nginx-status/tmp/tree_merger-tmp_dest_dir-9PxaKGt0.tmp//app/styles/app.scss',
     start: 1423773635462,
     includedFiles: [ '/Users/ewout/Workspace/_Code/JavaScript/nginx-status/tmp/tree_merger-tmp_dest_dir-9PxaKGt0.tmp/app/styles/app.scss' ],
     end: 1423773635471,
     duration: 9 } }
```

It seems strange that even though ```sass.render``` calls node-sass'  ```binding.renderFile```, nothing is written to the provided outFile. This is where I got stuck and gave up. It's simple enough to write the resulting compiled css to the outFile in the broccoli plugin, but that seems more like a hack to me.

Just sharing my findings, hope this might be of some use.

**Comment by aexmachina** [comment]
This PR should be closed in favour of #43 because there's changes to the node-sass API, and that PR also provides support for `sourcesContent`, which is necessary in the case of broccoli.

Regarding the problem with install, I've hit the same issue with #43. I've got a release deadline today, would you mind following up that install issue with node-sass?

**Comment by deepflame** [comment]
I saw that you also upgraded to 2.0.1 now. Great, then I will close my pull request and hope that yours will be merged soon.

I opened an issue on node-sass. Feel free to add to this: https://github.com/sass/node-sass/issues/678

**Pull request closed without merging**
